name: docker build
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.base
          tags: |
            omnetpp-base:latest
            omnetpp-base:${{ github.sha }}
          outputs: type=docker,dest=/tmp/omnetpp-base.tar
      - name: Load image
        run: |
          docker images -a
          docker load --input /tmp/omnetpp-wasm.tar
      - name: Build and push ci image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.ci
          tags: |
            ghcr.io/${{ github.repository }}-ci:latest
            ghcr.io/${{ github.repository }}-ci:${{ github.sha }}
          # outputs: type=docker,dest=/tmp/omnetpp-ci.tard
      - name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.dev
          tags: |
            ghcr.io/${{ github.repository }}-dev:latest
            ghcr.io/${{ github.repository }}-dev:${{ github.sha }}
          # outputs: type=docker,dest=/tmp/omnetpp-dev.tar
