name: docker build
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build Docker Images
        run: make
